.\" Description: quickselect.3 version 1.0 man page 2017-02-02T19:43:19Z
.\" common man macros to V7, V10, DWB2 (unique ones omitted, differences noted)
.\" .TH n c x	V7,10	begin page n of chapter c; x is extra commentary
.\" .TH t s c n	DWB2	beg. pg. t of sect. s; c=extra comment, n=new man. name
.\"			c appears at bottom center of page, n at top center
.\" .SH text		subhead
.\" .SS text		sub-subhead
.\" .B text		make text bold
.\" .I text		make text italic
.\" .SM text		make text 1 point smaller than default
.\" .RI a b		concatenate and alternate Roman, Italic fonts <=6 args
.\" .IR .RB .BR .IB .BI	similar to .RI
.\" .PP			new paragraph
.\" .HP in		hanging paragraph with indent in
.\" .TP in		indented paragraph with hanging tag (on next line)
.\" .IP t in		indented paragraph with hanging tag t (arg 1)
.\" .RS in		increase relative indent by in
.\" .RE k		return to kth relative indent level (1-based)
.\" .DT			default tab settings
.\" .PD v		inter-paragraph spacing v (default 0.4v troff, 1v nroff)
.\" \*R			registered symbol	(Reg.)
.\" \*S			change to default type size
.lg 0	\" avoid groff's butt-ugly ligatures
.nh	\" no hyphenation
.ds ]W \" no 7th Edition designation
.\" package name in string xx
.ds xx quickselect
.\" copyright year(s) in string xy
.ds xy "2016-2017
.TH \*(xx 3 ""
.SH NAME	\" 1 line	name \- explanatory text
.B \*(xx
\- multiple selection of order statistics and sorting
.SH SYNOPSIS
.nh	\" no hyphenation
\fB#include <quickselect.h>\fP
.PP
.B void quickselect(void *base, size_t nmemb, const size_t size, int (*compar)(const void *, const void *), const size_t *pk, const size_t nk);
'\" QUICKSELECT_EXTERN void quickselect(void *, size_t, const size_t, int (*)(const void *, const void *), const size_t *, const size_t);
'\" QUICKSELECT_EXTERN void QSORT_FUNCTION_NAME(void *, size_t, size_t, int (*)(const void *, const void *));
.PP
.B void QSORT_FUNCTION_NAME(void *base, size_t nmemb, const size_t size, int (*compar)(const void , const void *));
.PP
.SH DESCRIPTION
The
.B \*(xx
function
implements
multiple selection of order statistics.
Given an array
.B pk
of
.B nk
.I size_t
elements representing
0\-based
order statistic indices,
.B \*(xx
partially orders the array
.B base
such that the
specified order statistics are
in\-place
in the array.
If
.B pk
is
.I NULL
or
.B nk
is 0UL,
a full sort of the array is performed.
.SH RETURN VALUES
none
.SH ERRORS
If
.B base
is
.IR NULL ,
.B nmemb
is
0UL,
.B size
is
0UL,
or
.B compar
is
.IR NULL ,
the global variable
.I errno
is set to
.BR EINVAL .
.SH EXAMPLES
.PP
size_t karray[2];
.br
karray[0] = (nmemb-1UL)/2UL;
.br
karray[1] = nmemb/2UL;
.br
\*(xx(base, nmemb, size, compar, karray, 2UL);
.br

.br
places the median
.RB ( nmemb \0odd)
or medians
.RB ( nmemb \0even)
in the middle
element(s) of the array
pointed to by
.BR base.
.br

.br
\*(xx(base, nmemb, size, compar, NULL, 0UL);
.br

.br
sorts the array.
.PP
.SH APPLICATION USAGE
If the macro
.B QSORT_FUNCTION_NAME
is defined before
\*(xx.h
is included
when compiling the
\*(xx.c source,
a sorting function with the same semantics as
.B qsort
is generated,
using the specified name.
A library implementation of
.B qsort
may be generated by defining
.B QSORT_FUNCTION_NAME
as
.BR qsort .
.SH RATIONALE
While many libraries include a standard
.B qsort
function,
the
.B qsort
implementation may tend to
quadratic performance on adverse inputs.
Few libraries provide a function for selection of order statistics.
.SH BUGS and CAVEATS
\*(xx 
has expected and worst\-case linear complexity for finding a single order statistic.
\*(xx 
has expected and worst\-case lineararithmic complexity for sorting.
.SH FUTURE DIRECTIONS
none
.SH SEE ALSO
qsort
.SH CHANGE HISTORY
Initial version January 2107.
.SH AUTHOR
Bruce Lilly <bruce.lilly@gmail.com>
.SH LICENSE
.PP
The following license covers this software, including makefiles and documentation:
.PP
This software is covered by the zlib/libpng license.
.br
The zlib/libpng license is a recognized open source license by the
Open Source Initiative: http://opensource.org/licenses/Zlib
.br
The zlib/libpng license is a recognized \(dqfree\(dq software license by the
Free Software Foundation: https://directory.fsf.org/wiki/License:Zlib
.br
.lt +0.6i
.po 0.7i
.tl '*************** 'Copyright notice (part of the license)'***************'
.po
.lt
.br
@(#)quickselect.3 1.0 2017-02-02T19:43:19Z copyright \*(xy Bruce Lilly
.br
This software is provided 'as-is', without any express or implied warranty.
In no event will the authors be held liable for any damages arising from the
use of this software.
.PP
Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it freely,
subject to the following restrictions:
.IP 1. 0.3i
The origin of this software must not be misrepresented; you must not claim
that you wrote the original software. If you use this software in a
product, an acknowledgment in the product documentation would be
appreciated but is not required.
.IP 2. 0.3i
Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.
.IP 3. 0.3i
This notice may not be removed or altered from any source distribution.
.RS 0
.lt +0.6i
.po 0.7i
.tl '*************************'(end of license)'*************************'
.po
.lt
.PP
You may send bug reports to bruce.lilly@gmail.com with subject "\*(xx".
.\" maintenance note: master file  /data/projects/automation/940/lib/libmedian/man/s.quickselect.3
