/*INDENT OFF*/

/* Description: C source code for quickselect tables */
/******************************************************************************
* This software is covered by the zlib/libpng license.
* The zlib/libpng license is a recognized open source license by
* the Open Source Initiative: http://opensource.org/licenses/Zlib
* The zlib/libpng license is a recognized "free" software license by
* the Free Software Foundation: https://directory.fsf.org/wiki/License:Zlib
*******************************************************************************
******************* Copyright notice (part of the license) ********************
* $Id: ~|^` @(#)    repivot_tables.c copyright 2017 Bruce Lilly.   \ repivot_tables.c $
* This software is provided 'as-is', without any express or implied warranty.
* In no event will the authors be held liable for any damages arising from the
* use of this software.
*
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it freely,
* subject to the following restrictions:
*
* 1. The origin of this software must not be misrepresented; you must not claim
*    that you wrote the original software. If you use this software in a
*    product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
*
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
*
* 3. This notice may not be removed or altered from any source distribution.
****************************** (end of license) ******************************/
/* $Id: ~|^` @(#)   This is repivot_tables.c version 1.4 dated 2018-05-18T01:35:57Z. \ $ */
/* You may send bug reports to bruce.lilly@gmail.com with subject "quickselect" */
/*****************************************************************************/
/* maintenance note: master file /data/projects/automation/940/lib/libmedian/src/s.repivot_tables.c */

/********************** Long description and rationale: ***********************
 Partitioning can result in an unfavorable split of the initial sub-array;
 when this happens, an emergency "break-glass" pivot selection function is used
 to ensure a better split, avoiding quadratic behavior even when handling a
 worst-case input array, such as can be generated by an adversary function
 (M. D. McIlroy "A Killer Adversary for Quicksort").
 The tables defined by this file determine how lopsided a prtition may be before
 the large region is repartitioned.
******************************************************************************/

/* Nothing to configure below this line. */

/* ID_STRING_PREFIX file name and COPYRIGHT_DATE are constant, other components
   are version control fields.
   ID_STRING_PREFIX is suitable for the what(1) and ident(1) utilities.
   MODULE_DATE uses modern SCCS extensions.
*/
#undef ID_STRING_PREFIX
#undef SOURCE_MODULE
#undef MODULE_VERSION
#undef MODULE_DATE
#undef COPYRIGHT_HOLDER
#undef COPYRIGHT_DATE
#define ID_STRING_PREFIX "$Id: repivot_tables.c ~|^` @(#)"
#define SOURCE_MODULE "repivot_tables.c"
#define MODULE_VERSION "1.4"
#define MODULE_DATE "2018-05-18T01:35:57Z"
#define COPYRIGHT_HOLDER "Bruce Lilly"
#define COPYRIGHT_DATE "2017"

/* local header files needed */
#include "quickselect_config.h" /* SORTING_TABLE_ENTRIES */
#include "tables.h"             /* struct repivot_table_struct */

/* system header files */
#include <stddef.h>             /* size_t */

/* data structures */
/*
   Repivoting with median-of medians always results in a ratio of the large
      region size to the remaining elements less than 3:1 (worst case is at size
      8 (2 sets of 3, with 2 elements left over; largest possible large region
      size is 6 for a ratio of 3:1), but sub-arrays of size 8 are never
      repivoted; the practical worst case is then at size 14 (4 sets of 3, with
      2 elements left over; worst case large region size 10 for a ratio of
      5:2)).
   With 729 or more samples, the ratio of the large region size to the remaining
      elements is rarely as high as 3:1, so factor2 and factor1 for those
      repivot table entries can safely be set to 3UL without any noticeable
      effect on the performance for random and/or frequently encountered
      structured input sequences.
   The factor2 member is set by finding the worst-case adversarial performance
      for sorting and for selection, and reducing the factor2 value at the
      appropriate max_nmemb entry to eliminate that worst-case performance,
      repeating the process until some desired absolute worst-case is achieved
      or the worst-case performance point cannot be eliminated by reducing
      factor2.
   When factor2 reduction is no longer able to eliminate a worst-case
      performance point, factor1 may be reduced to eliminate the worst-case
      performance point. This may be repeated (after first trying factor2!)
      until a desired absolute worst-case performance point is reached, no
      further improvement can be obtained using factor2 and factor1, or the
      elimination of a worst-case performance point entails too large of a
      performance penalty for random input sequences.
   The "disabled" and "transparent" repivot table factor1 and factor2 entries
      for 243 and fewer samples are set such that repivoting 'never' occurs for
      random input sequences for different variations of 'never', where 'never'
      represents some very low probability.
   The "loose" table entries are set to achieve a worst-case sorting comparison
      complexity of <= 2.0 N log(N) comparisons without further affecting random
      input sequences.
   The "relaxed" table entries are set to achieve the minimum comparison
      complexities possible for sorting using primarily factor2, and only
      decreasing factor1 when absolutely necessary.
   The "aggressive" table entries use both factors as far as possible (i.e.
      until some worst-case performance point cannot be eliminated or the
      performance penalty becomes too great).
*/
/* repivot factors are relatively small unsigned integers */

/* sorting repivot tables */
struct repivot_table_struct sorting_repivot_table_transparent[] = {
/*
transparent factors=-1 13,41,79,79,13,6,4 -2 12,40,78,78,12,5,3 -7 13,41,79,79,13,6,4 -8 12,40,78,78,12,5,3
sorting average 0.995298 factors=-1 13,41,79,79,13,6,4 -2 12,40,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
sorting 3.35538@80 factors=-1 13,41,79,79,13,6,4 -2 12,40,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
*/
  /* 1 */ {  13U,  12U }, /* sorting transparent */ /* single sample */
  /* 3 */ {  41U,  40U }, /* sorting transparent */ /* median-of-3 */
  /* 9 */ {  79U,  13U }, /* sorting transparent */ /* remedian of samples */
 /* 27 */ {  79U,   6U }, /* sorting transparent */
 /* 81 */ {  13U,  12U }, /* sorting transparent */
/* 243 */ {   6U,   5U }, /* sorting transparent */
/* 729 */ {   4U,   3U }, /* sorting transparent */
};
struct repivot_table_struct sorting_repivot_table_loose[] = {
/*
sorting 1.97187@35 factors=-1 13,41,79,79,13,6,4 -2 12,16,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
*/
  /* 1 */ {  13U,  12U }, /* sorting loose */ /* single sample */
  /* 3 */ {  41U,  16U }, /* sorting loose */ /* median-of-3 */
  /* 9 */ {  79U,  13U }, /* sorting loose */ /* remedian of samples */
 /* 27 */ {  79U,   6U }, /* sorting loose */
 /* 81 */ {  13U,  12U }, /* sorting loose */
/* 243 */ {   6U,   5U }, /* sorting loose */
/* 729 */ {   4U,   3U }, /* sorting loose */
};
struct repivot_table_struct sorting_repivot_table_relaxed[] = {
/*
sorting 1.59639@79 factors=-1 13,41,79,79,13,6,4 -2 10,10,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
export factors="-1 9,10,23,79,13,6,4 -2 8,10,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3"
90  1.46508 N log(N) mean comparisons [856-856] (856)
sorting 1.48464@48 factors=-1 13,24,79,79,13,6,4 -2 9,8,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
*/
  /* 1 */ {  13U,   9U }, /* sorting relaxed */ /* single sample */
  /* 3 */ {  24U,   8U }, /* sorting relaxed */ /* median-of-3 */
  /* 9 */ {  79U,  13U }, /* sorting relaxed */ /* remedian of samples */
 /* 27 */ {  79U,   6U }, /* sorting relaxed */
 /* 81 */ {  13U,  12U }, /* sorting relaxed */
/* 243 */ {   6U,   5U }, /* sorting relaxed */
/* 729 */ {   4U,   3U }, /* sorting relaxed */
};
struct repivot_table_struct sorting_repivot_table_aggressive[] = {
/*
export factors="-1 9,10,21,79,13,6,4 -2 8,10,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3"
20  1.43454 N log(N) mean comparisons [124-124] (124)
sorting 1.39428@27 factors=-1 13,14,20,64,13,6,4 -2 9,6,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
*/
  /* 1 */ {  13U,   9U }, /* sorting aggressive */ /* single sample */
  /* 3 */ {  14U,   6U }, /* sorting aggressive */ /* median-of-3 */
  /* 9 */ {  20U,  13U }, /* sorting aggressive */ /* remedian of samples */
 /* 27 */ {  64U,   6U }, /* sorting aggressive */
 /* 81 */ {  13U,  12U }, /* sorting aggressive */
/* 243 */ {   6U,   5U }, /* sorting aggressive */
/* 729 */ {   4U,   3U }, /* sorting aggressive */
};
struct repivot_table_struct sorting_repivot_table_disabled[] = {
  /* 1 */ { 255U, 255U }, /* disabled */
  /* 3 */ { 255U, 255U }, /* disabled */
  /* 9 */ { 255U, 255U }, /* disabled */
 /* 27 */ { 255U, 255U }, /* disabled */
 /* 81 */ { 255U, 255U }, /* disabled */
/* 243 */ { 255U, 255U }, /* disabled */
/* 729 */ { 255U, 255U }, /* disabled */
};

struct repivot_table_struct *sorting_repivot_table =
#if SORTING_TABLE_ENTRIES == TRANSPARENT
    sorting_repivot_table_transparent
#elif SORTING_TABLE_ENTRIES == LOOSE
    sorting_repivot_table_loose
#elif SORTING_TABLE_ENTRIES == RELAXED
    sorting_repivot_table_relaxed
#elif SORTING_TABLE_ENTRIES == AGGRESSIVE
    sorting_repivot_table_aggressive
#else
    sorting_repivot_table_disabled
#endif
;

/* selection repivot table; always very aggressive due to the much greater
   sensitivity of selection performance to lopsided partitions.
*/
struct repivot_table_struct selection_repivot_table[] = {
/*
r3 selection 3.52239@1340 factors=-1 13,41,79,79,13,6,4 -2 12,40,53,78,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
d5 selection 8.56064@503 factors=-1 13,41,79,79,13,6,4 -2 12,40,13,6,12,5,3 -7 11,6,13,18,13,6,4 -8 9,3,5,12,12,5,3
*/
  /* 1 */ {  11U,   9U }, /* selection aggressive */ /* single sample */
  /* 3 */ {   6U,   3U }, /* selection aggressive */ /* median-of-3 */
  /* 9 */ {  13U,   5U }, /* selection aggressive */ /* remedian of samples */
 /* 27 */ {  18U,  12U }, /* selection aggressive */
 /* 81 */ {  13U,  12U }, /* selection aggressive */
/* 243 */ {   6U,   5U }, /* selection aggressive */
/* 729 */ {   4U,   3U }, /* selection aggressive */
};

/* All repivot tables have the same size. */
const size_t repivot_table_size
    = sizeof(selection_repivot_table)/sizeof(selection_repivot_table[0]);
