/*INDENT OFF*/

/* Description: C source code for select_pivot */
/******************************************************************************
* This software is covered by the zlib/libpng license.
* The zlib/libpng license is a recognized open source license by
* the Open Source Initiative: http://opensource.org/licenses/Zlib
* The zlib/libpng license is a recognized "free" software license by
* the Free Software Foundation: https://directory.fsf.org/wiki/License:Zlib
*******************************************************************************
******************* Copyright notice (part of the license) ********************
* $Id: ~|^` @(#)    pivot_src.h copyright 2017 Bruce Lilly.   \ pivot_src.h $
* This software is provided 'as-is', without any express or implied warranty.
* In no event will the authors be held liable for any damages arising from the
* use of this software.
*
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it freely,
* subject to the following restrictions:
*
* 1. The origin of this software must not be misrepresented; you must not claim
*    that you wrote the original software. If you use this software in a
*    product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
*
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
*
* 3. This notice may not be removed or altered from any source distribution.
****************************** (end of license) ******************************/
/* $Id: ~|^` @(#)   This is pivot_src.h version 1.8 dated 2017-12-22T04:14:04Z. \ $ */
/* You may send bug reports to bruce.lilly@gmail.com with subject "quickselect" */
/*****************************************************************************/
/* maintenance note: master file /data/projects/automation/940/lib/libmedian/include/s.pivot_src.h */

/********************** Long description and rationale: ***********************
 Pivot selection uses Rousseeuw & Basset's remedian, described in "The Remedian:
 A Robust Averaging Method for Large Data Sets", on a sample of a size which is
 a power of 3 taken from the array elements, with sample size approximately the
 square root of the array size as described in "Optimal Sampling Strategies for
 Quicksort" by McGeoch and Tygar, and in "Optimal Sampling Strategies in
 Quicksort and Quickselect" by Martinez and Roura.
 Elements sampled from the array for use by the pivot selection methods are
 chosen to provide good overall performance, avoiding choices that would fare
 poorly for commonly-seen input sequences (e.g. organ-pipe, already-sorted).
 Partitioning uses a method described by Bentley & McIlroy, with a modification
 to reduce disorder induced in arrays.
 Comparisons are made between array elements; there is no special-case code nor
 initialization macro.
 Partitioning can still result in an unfavorable split of the initial sub-array;
 when this happens, an emergency "break-glass" pivot selection function is used
 to ensure a better split, avoiding quadratic behavior even when handling a
 worst-case input array, such as can be generated by an adversary function
 (M. D. McIlroy "A Killer Adversary for Quicksort").
 Break-glass pivot selection uses median-of-medians using sets of 3 elements
 (ignoring leftovers) and using a call to quickselect to find the median of
 medians, rather than recursion.  Aside from those details, it is similar to the
 method described by Blum, Floyd, Pratt, Rivest, & Tarjan in "Time Bounds for
 Selection".
******************************************************************************/

/* Minimum _XOPEN_SOURCE version for C99 (else illumos compilation fails) */
#undef MAX_XOPEN_SOURCE_VERSION
#undef MIN_XOPEN_SOURCE_VERSION
#if defined(__STDC__) && ( __STDC_VERSION__ >= 199901L)
# define MIN_XOPEN_SOURCE_VERSION 600 /* >=600 for illumos */
#else
# define MAX_XOPEN_SOURCE_VERSION 500 /* <=500 for illumos */
#endif

/* feature test macros defined before any header files are included */
#ifndef _XOPEN_SOURCE
# ifdef MIN_XOPEN_SOURCE_VERSION
#  define _XOPEN_SOURCE MIN_XOPEN_SOURCE_VERSION
# else
#  ifdef MAX_XOPEN_SOURCE_VERSION
#   define _XOPEN_SOURCE MAX_XOPEN_SOURCE_VERSION
#  endif
# endif
#endif
#if defined(_XOPEN_SOURCE) \
&& defined(MIN_XOPEN_SOURCE_VERSION) \
&& ( _XOPEN_SOURCE < MIN_XOPEN_SOURCE_VERSION )
# undef _XOPEN_SOURCE
# define _XOPEN_SOURCE MIN_XOPEN_SOURCE_VERSION
#endif
#if defined(_XOPEN_SOURCE) \
&& defined(MAX_XOPEN_SOURCE_VERSION) \
&& ( _XOPEN_SOURCE > MAX_XOPEN_SOURCE_VERSION )
# undef _XOPEN_SOURCE
# define _XOPEN_SOURCE MAX_XOPEN_SOURCE_VERSION
#endif

#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif

/* ID_STRING_PREFIX file name and COPYRIGHT_DATE are constant, other components
   are version control fields.
   ID_STRING_PREFIX is suitable for the what(1) and ident(1) utilities.
   MODULE_DATE uses modern SCCS extensions.
*/
#undef ID_STRING_PREFIX
#undef SOURCE_MODULE
#undef MODULE_VERSION
#undef MODULE_DATE
#undef COPYRIGHT_HOLDER
#undef COPYRIGHT_DATE
#define ID_STRING_PREFIX "$Id: pivot_src.h ~|^` @(#)"
#define SOURCE_MODULE "pivot_src.h"
#define MODULE_VERSION "1.8"
#define MODULE_DATE "2017-12-22T04:14:04Z"
#define COPYRIGHT_HOLDER "Bruce Lilly"
#define COPYRIGHT_DATE "2017"

/* local header files needed */
#include "exchange.h"           /* EXCHANGE_SWAP */
#include "quickselect_config.h" /* QUICKSELECT_INLINE */
#include "tables.h"             /* sampling_table_struct SAMPLING_TABLE_SIZE */
#if ! QUICKSELECT_BUILD_FOR_SPEED
#include "initialize_src.h"
#endif /* QUICKSELECT_BUILD_FOR_SPEED */

/* for assert.h */
#if ! ASSERT_CODE
# define NDEBUG 1
#endif

/* system header files */
#include <assert.h>             /* assert */
#include <errno.h>              /* errno E* (maybe errno_t [N1570 K3.2]) */
#include <stddef.h>             /* size_t NULL (maybe rsize_t) */
#if defined(__STDC__) && ( __STDC_VERSION__ >= 199901L)
# if __STDC_VERSION__ >= 201001L
    /* [N1570 6.10.8.1] (minimum value: y=0,mm=01) */
#  include <stdio.h>            /* (maybe errno_t rsize_t [N1570 K3.5]) */
#  include <stdlib.h>           /* (maybe errno_t rsize_t constraint_handler_t
                                   [N1570 K3.6]) */
# endif /* N1570 */
#endif /* C99 or later */

#if __STDC_WANT_LIB_EXT1__
/* Preliminary support for 9899:201x draft N1570 qsort_s w/ "context".
   "context" is similar to glibc qsort_r; N1570 also has provision for
   runtime-constraint violation detection and handling. "Preliminary"
   because of the apparent lack of a convincing use-case for "context" and
   due to the poorly defined semantics and interface for constraint
   violation handling.

   Consequences of "context" are wide-ranging: any operation that requires
   comparisons (pivot selection, partitioning, dedicated sorting and/or
   selection, and support functions for any of those) has to be rewritten.
   The only operations unaffected are sampling, basic swaps, blockmoves using
   swaps, rank comparisons, and partition size evaluation; sampling and
   repivoting tables may also be reused without change.
   Executable code size is roughly doubled, not including external
   constraint-handler function code.
   Use case of "context" is questionable; one could simply use an appropriate
   comparison function.  Published supposed examples (e.g.
   https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort-s
   tend to be rather silly (in the specific example above:
      1. functions are defined for specific locales, but not specifically
         implementing locale-specific collation -- one could at least as easily
         define locale-specific string comparison functions using the standard
         strcoll [+] function and use these with qsort to perform the
         locale-specific sorts with no need for "context", and avoiding the
         other implementation issues detailed below.
      2. Aside from inconsistent "context" argument order...
      3. ... the implementation comparison function copies (!) (leading portions
         of) supplied strings to fixed size (!!)[*] local buffers, then makes a
         second set of passes (!!!) over the copies to perform a conversion
         (which is discarded (!!!!) when the comparison function returns), which
         is then subjected to a third (!!!!!) pass to perform the comparison.
         Note that qsort implementations typically call the comparison function
         N log N times for an array of N elements; the above implementation
         makes 2 N log N copies and 6 N log N passes over data representing
         the strings to be sorted.  In particular, at each stage of partitioning
         qsort implementations compare a pivot element to many other elements;
         in the above implementation the string corresponding to that pivot
         element is copied, the copy modified and examined, only to be discarded
         before repeating those steps anew with the same pivot element's string
         for the next comparison.
      4. Although the copies (see #3 above) ignore the actual length of the
         original strings, strlen is subsequently called for each string (copy),
         resulting in a fourth (!!!!!!) pass over the data. Had strlen been
         called for the initial strings, the copies could have been made
         appropriate sizes (assuming that one still naively wished to make, then
         discard such copies).
      * a possibly-valid use of "context" *might* be to provide the maximum
        string length, avoiding magic numbers and failure to fully compare
        strings which have long identical leading substrings... *if* one
        insisted on the naive implementation involving copies (which are
        subsequently discarded) and multiple passes over the data.  It would
        be much more efficient to make one-time initial transformations (e.g.
        w/ strxfrm [+]) of the original string data supplemented by an index
        indicating the original order (or a pointer to the original string
        data), sorting the transformed and supplemented data using standard
        strcmp on the transformed strings.  That would involve N combined
        transformations and copies (instead of N log N copies and N log N
        transformations) plus N log N standard strcmp string comparisons (rather
        than 6 N log N passes over data), followed by access of the orginal
        string data via the indices or pointers for output.
      + Note that strcoll and strxfrm have been standardized since C89 (a.k.a.
        C90).
   ). In summary, there is no convincing use-case for "context" to justify
   doubling the size of library code.
*/
#endif /* __STDC_WANT_LIB_EXT1__ */

/* medians of sets of 3 elements */
/* 3 elements:
   Optimized ternary median-of-3: 1-3 comparisons.
   Minimum number of comparisons (because in the qsort model (external function
   for comparison), comparisons are expensive).  If any two elements (of the 3)
   compare equal, either can be chosen for the median (the value is the median
   of the 3, regardless of the value of the third element).  Likewise, the
   median may be determined by the first two comparisons, e.g. a < b and b < c.
   In the worst case, 3 comparisons are required.
   Return value is biased to pb, then pa.
*/
/* called from remedian and select_pivot */
static QUICKSELECT_INLINE
char *FMED3_FUNCTION_NAME(char *pa,char *pb,char *pc,COMPAR_DECL,unsigned int options)
{
    register int c;
#if QUICKSELECT_INDIRECT
    A(0U==(options&(QUICKSELECT_INDIRECT))); /* dereferenced by caller */
#endif /* QUICKSELECT_INDIRECT */
    c=COMPAR(pa,pb,context);
    if (0!=c) {
        int d=COMPAR(pb,pc,context);
        if (0!=d) {
            if ((0<d)&&(0>c)) {
                if (0>COMPAR(pa,pc,context)) return pc;
                else return pa;
            } else if ((0>d)&&(0<c)) {
                if (0<COMPAR(pa,pc,context)) return pc;
                else return pa;
            }
        }
    }
    return pb;
}

/* Remedian (base 3) of samples, recursive implementation. */
/* top-level call from select_pivot */
/* idx is the index into the sampling table (with number of samples equal to
      the idx'th power of 3), which provides a cheap way of determining when to
      end the recursion
*/
/* row_spacing and sample_spacing are measured in elements, converted to chars
      here for offsets to middle element
*/
/* Uniform sample spacing is maintained, recursively. */
static QUICKSELECT_INLINE
char *REMEDIAN_FUNCTION_NAME(char *middle, size_t row_spacing, size_t sample_spacing,
    size_t size, unsigned int idx, COMPAR_DECL, unsigned int options)
{
    size_t o;
    if (0U < --idx) {
        char *pa, *pb, *pc;
        size_t s=sample_spacing/3UL;

        o=s*size;
        pa=REMEDIAN_FUNCTION_NAME(middle-o,row_spacing,s,size,idx,COMPAR_ARGS,options);
        pb=REMEDIAN_FUNCTION_NAME(middle,row_spacing,s,size,idx,COMPAR_ARGS,options);
        pc=REMEDIAN_FUNCTION_NAME(middle+o,row_spacing,s,size,idx,COMPAR_ARGS,options);
#if QUICKSELECT_INDIRECT
        if (0U==(options&(QUICKSELECT_INDIRECT)))
#endif /* QUICKSELECT_INDIRECT */
            return FMED3_FUNCTION_NAME(pa,pb,pc,COMPAR_ARGS,options);
#if QUICKSELECT_INDIRECT
        else {
            char *pr= FMED3_FUNCTION_NAME(*((char **)pa),*((char **)pb),
                *((char **)pc),COMPAR_ARGS,options&~(QUICKSELECT_INDIRECT));
            if (pr==*((char **)pa)) return pa;
            if (pr==*((char **)pc)) return pc;
            return pb;
        }
#endif /* QUICKSELECT_INDIRECT */
    }
    o=row_spacing*size;
#if QUICKSELECT_INDIRECT
    if (0U==(options&(QUICKSELECT_INDIRECT)))
#endif /* QUICKSELECT_INDIRECT */
        return FMED3_FUNCTION_NAME(middle-o,middle,middle+o,COMPAR_ARGS,options);
#if QUICKSELECT_INDIRECT
    else {
        char *pa, *pc, *pr;
        pa=middle-o, pc=middle+o;
        pr = FMED3_FUNCTION_NAME(*((char **)pa),*((char **)middle),
            *((char **)pc),COMPAR_ARGS,options&~(QUICKSELECT_INDIRECT));
        if (pr==*((char **)pa)) return pa;
        if (pr==*((char **)pc)) return pc;
        return middle;
    }
#endif /* QUICKSELECT_INDIRECT */
}

#if ! QUICKSELECT_BUILD_FOR_SPEED
/* sampling_table declaration */
#include "sampling_table_decl.h"
;

/* declaration */
#include "select_pivot_decl.h"
;
#endif /* QUICKSELECT_BUILD_FOR_SPEED */

/* clutter removal */
#undef PREFIX
#undef SUFFIX2
#if __STDC_WANT_LIB_EXT1__
# define PREFIX A(0==ret);ret=
# define SUFFIX2 A(0==ret);if(0!=ret)return NULL;
#else
# define PREFIX /**/
# define SUFFIX2 /**/
#endif /* __STDC_WANT_LIB_EXT1__ */

/* select_pivot using remedian or median-of-medians */
/* Called from both loop functions. */
#if QUICKSELECT_BUILD_FOR_SPEED
static QUICKSELECT_INLINE
#endif /* QUICKSELECT_BUILD_FOR_SPEED */
#include "select_pivot_decl.h"
{
    size_t nmemb=beyond-first;
    register size_t n, r=nmemb/3UL;     /* 1/3 #elements */
    char *pivot;

#if ! QUICKSELECT_BUILD_FOR_SPEED
    if ((char)0==file_initialized) initialize_file(__FILE__);
#endif /* QUICKSELECT_BUILD_FOR_SPEED */
    A((SAMPLING_TABLE_SIZE)>table_index);
    switch (options&((QUICKSELECT_STABLE)|(QUICKSELECT_RESTRICT_RANK))) {
#if QUICKSELECT_STABLE
        case ((QUICKSELECT_RESTRICT_RANK)|(QUICKSELECT_STABLE)) :
            /* almost full remedian */
            while (table_index<(SAMPLING_TABLE_SIZE)-1U) {
                n=sorting_sampling_table[table_index].samples;
                if (n>r) break;
                table_index++;
            }
            while ((n=sorting_sampling_table[table_index].samples)>r)
                table_index--;
            if (table_index==(SAMPLING_TABLE_SIZE)-1U) {
                for (; n<r; table_index++)
                    n*=3UL;
                if (n>r) table_index--;
            }
        /*FALLTHROUGH*/
#endif
        default:
            /*Fast pivot selection:1 sample, median-of-3, remedian of samples.*/
            pivot=base+size*(first+(nmemb>>1));     /* [upper-]middle element */
            if (0U<table_index) {       /* 3 or more samples */
                A(base+first*size<=pivot);A(pivot<base+beyond*size);
                pivot=REMEDIAN_FUNCTION_NAME(pivot,r,r,size,table_index,
                    COMPAR_ARGS,options);
            }
            *ppc=*ppd=pivot, *ppe=*ppf=pivot+size;
        break;
        case (QUICKSELECT_RESTRICT_RANK) :
            /* rearranges elements; precludes stable sort/selection */
            {   size_t karray[1];
                register size_t o;
                register char *pa, *pb, *pc, *pm;
#if __STDC_WANT_LIB_EXT1__
                errno_t ret=0;
#endif /* __STDC_WANT_LIB_EXT1__ */

                A(NULL!=base);A(NULL!=compar);
                A(8UL<nmemb); /* at least 9 elements (3 sets of 3) */
                A((SAMPLING_TABLE_SIZE)>table_index);
                A(NULL!=ppc);A(NULL!=ppd);A(NULL!=ppe);A(NULL!=ppf);
                /* Finding a pivot with guaranteed intermediate rank. Ideally,
                   median (50%).  Blum, Floyd, Pratt, Rivest, Tarjan
                   median-of-medians using sets of 5 elements with recursion
                   guarantees rank in (asymptotically) 30-70% range, often
                   better; can guarantee linear median-finding, N log(N)
                   sorting. Simplification ignores "leftover" elements with a
                   slight increase in rank range.  Non-recursive method (using
                   separate linear median finding) can use sets of 3 elements to
                   provide a tighter 33.33% to 66.67% range (again, slightly
                   wider if "leftover" elements are ignored) at lower
                   computational cost.
                */
                pc=base+first*size;
                /* Medians of sets of 3 elements. */
                A(1UL<r); /* never repivot for nmemb<9 */
                /*3 element sets (columns); medians->1st row, ignore leftovers*/
                for (o=0UL,n=r*size; o<n; o+=size) {
                    pa=pc+o;
                    pb=pa+n; /* middle element */
                    A(pb+n<base+beyond*size);
#if QUICKSELECT_INDIRECT
                    if (0U==(options&(QUICKSELECT_INDIRECT))) {
#endif /* QUICKSELECT_INDIRECT */
                        pm=FMED3_FUNCTION_NAME(pb,pa,pb+n,COMPAR_ARGS,options); /*bias pa*/
                        if (pm!=pa) { /* place medians at start of sub-array */
                            EXCHANGE_SWAP(swapf,pm,pa,size,alignsize,size_ratio,/**/);
                        }
#if QUICKSELECT_INDIRECT
                    } else {
                        pm=FMED3_FUNCTION_NAME(*((char **)pb),*((char **)pa),
                            *((char **)(pb+n)),COMPAR_ARGS,
                            options&~(QUICKSELECT_INDIRECT));
                        /*medians at start of sub-array*/
                        /*compare returned data pointer,swap indirect pointers*/
                        if (pm!=*((char **)pa)) {
                            if (pm==*((char **)pb))
                                EXCHANGE_SWAP(swapf,pa,pb,size,alignsize,
                                    size_ratio,/**/);
                            else
                                EXCHANGE_SWAP(swapf,pa,pb+n,size,alignsize,
                                    size_ratio,/**/);
                        }
                    }
#endif /* QUICKSELECT_INDIRECT */
                }
                *ppc=pc; /* first median */
                /* median of medians */
                karray[0]=first+(r>>1); /* upper-median for even size arrays */
                beyond=first+r; /* past last median */
                A(first<=karray[0]);A(karray[0]<beyond);
                *ppf=base+beyond*size; /* past last median */
# if ASSERT_CODE
                A((NULL!=ppd)&&(NULL!=ppe));
                *ppd=*ppe=NULL; /* clear to avoid random values */
# endif
                /* select median of medians; partitions medians */
                PREFIX QUICKSELECT_LOOP(base,first,beyond,size,COMPAR_ARGS,
                    karray,0UL,1UL,swapf,alignsize,size_ratio,1UL,
                    QUICKSELECT_NETWORK_MASK,NULL,NULL,NULL,ppd,ppe); SUFFIX2
                pivot=base+karray[0]*size; /* pointer to median of medians */
                /* First third of array (medians) is partitioned. */
            }
        break;
    }
    A(NULL!=pivot);A(base+first*size<=pivot);A(pivot<base+beyond*size);
    A(*ppd<=pivot);A(pivot<*ppe);A(*ppc<=*ppd);A(*ppe<=*ppf);
    return pivot;
}
