#ifndef QUICKSELECT_LOOP_SRC_H_INCLUDED
# define QUICKSELECT_LOOP_SRC_H_INCLUDED 1
/*INDENT OFF*/

/* Description: C source code for quickselect_loop */
/******************************************************************************
* This software is covered by the zlib/libpng license.
* The zlib/libpng license is a recognized open source license by
* the Open Source Initiative: http://opensource.org/licenses/Zlib
* The zlib/libpng license is a recognized "free" software license by
* the Free Software Foundation: https://directory.fsf.org/wiki/License:Zlib
*******************************************************************************
******************* Copyright notice (part of the license) ********************
* $Id: ~|^` @(#)    quickselect_loop_src.h copyright 2017-2018 Bruce Lilly.   \ quickselect_loop_src.h $
* This software is provided 'as-is', without any express or implied warranty.
* In no event will the authors be held liable for any damages arising from the
* use of this software.
*
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it freely,
* subject to the following restrictions:
*
* 1. The origin of this software must not be misrepresented; you must not claim
*    that you wrote the original software. If you use this software in a
*    product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
*
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
*
* 3. This notice may not be removed or altered from any source distribution.
****************************** (end of license) ******************************/
/* $Id: ~|^` @(#)   This is quickselect_loop_src.h version 1.20 dated 2018-04-18T04:09:58Z. \ $ */
/* You may send bug reports to bruce.lilly@gmail.com with subject "quickselect" */
/*****************************************************************************/
/* maintenance note: master file /data/projects/automation/940/lib/libmedian/include/s.quickselect_loop_src.h */

/********************** Long description and rationale: ***********************
 An implementation of multiple quickselect similar to that described by Mahmoud
 & Lent in "Average-case analysis of multiple Quickselect: An algorithm for
 finding order statistics".  The array of items to be sorted by quickselect,
 the array element size, and the comparison function are declared as for qsort,
 with two additional parameters to specify an optional array of desired order
 statistic ranks.
 N.B. the values for the order-statistic array elements are zero-based ranks
 (i.e. 0UL for the minimum, N-1UL for the maximum of an array of N elements,
 (N-1UL)/2UL and N/2UL for the lower- and upper-medians).
 The implementation can also be used to implement qsort; a wrapper function
 (which could alternatively be implemented as a macro) is provided for that
 purpose.
 In order to be able to compute the rank of array elements for selection, the
 initial array base is maintained, and a pair of indices brackets the sub-array
 being processed.  The indices correspond to the ranks of elements.  A similar
 scheme is used by Musser's introsort, described in "Introspective Sorting and
 Selection Algorithms".  The same method is used for the array of desired order
 statistic ranks, similar to that described by Lent & Mahmoud.
 Pivot selection uses Rousseeuw & Basset's remedian, described in "The Remedian:
 A Robust Averaging Method for Large Data Sets", on a sample of a size which is
 a power of 3 taken from the array elements, with sample size approximately the
 square root of the array size as described in "Optimal Sampling Strategies for
 Quicksort" by McGeoch and Tygar, and in "Optimal Sampling Strategies in
 Quicksort and Quickselect" by Martinez and Roura.
 Elements sampled from the array for use by the pivot selection methods are
 chosen to provide good overall performance, avoiding choices that would fare
 poorly for commonly-seen input sequences (e.g. organ-pipe, already-sorted).
 Partitioning uses a method described by Bentley & McIlroy, with a modification
 to reduce disorder induced in arrays.
 Comparisons are made between array elements; there is no special-case code nor
 initialization macro.
 Partitioning can still result in an unfavorable split of the initial sub-array;
 when this happens, an emergency "break-glass" pivot selection function is used
 to ensure a better split, avoiding quadratic behavior even when handling a
 worst-case input array, such as can be generated by an adversary function
 (M. D. McIlroy "A Killer Adversary for Quicksort").
 Break-glass pivot selection uses median-of-medians using sets of 3 elements
 (ignoring leftovers) and using a call to quickselect to find the median of
 medians, rather than recursion.  Aside from those details, it is similar to the
 method described by Blum, Floyd, Pratt, Rivest, & Tarjan in "Time Bounds for
 Selection".
 Swapping of elements is handled by efficient inline swap functions.  No attempt
 is made to optimize for specific array element types, but swapping can be
 performed in units of basic language types.  The swap functions avoid useless
 work (e.g. when given two pointers to the same element).  No specialized macros
 are required.
******************************************************************************/

/* Nothing to configure below this line. */
/* Minimum _XOPEN_SOURCE version for C99 (else illumos compilation fails) */
#undef MAX_XOPEN_SOURCE_VERSION
#undef MIN_XOPEN_SOURCE_VERSION
#if defined(__STDC__) && ( __STDC__ == 1) && defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
# define MIN_XOPEN_SOURCE_VERSION 600 /* >=600 for illumos */
#else
# define MAX_XOPEN_SOURCE_VERSION 500 /* <=500 for illumos */
#endif

/* feature test macros defined before any header files are included */
#ifndef _XOPEN_SOURCE
# ifdef MIN_XOPEN_SOURCE_VERSION
#  define _XOPEN_SOURCE MIN_XOPEN_SOURCE_VERSION
# else
#  ifdef MAX_XOPEN_SOURCE_VERSION
#   define _XOPEN_SOURCE MAX_XOPEN_SOURCE_VERSION
#  endif
# endif
#endif
#if defined(_XOPEN_SOURCE) \
&& defined(MIN_XOPEN_SOURCE_VERSION) \
&& ( _XOPEN_SOURCE < MIN_XOPEN_SOURCE_VERSION )
# undef _XOPEN_SOURCE
# define _XOPEN_SOURCE MIN_XOPEN_SOURCE_VERSION
#endif
#if defined(_XOPEN_SOURCE) \
&& defined(MAX_XOPEN_SOURCE_VERSION) \
&& ( _XOPEN_SOURCE > MAX_XOPEN_SOURCE_VERSION )
# undef _XOPEN_SOURCE
# define _XOPEN_SOURCE MAX_XOPEN_SOURCE_VERSION
#endif

#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif

/* ID_STRING_PREFIX file name and COPYRIGHT_DATE are constant, other components
   are version control fields.
   ID_STRING_PREFIX is suitable for the what(1) and ident(1) utilities.
   MODULE_DATE uses modern SCCS extensions.
*/
#undef ID_STRING_PREFIX
#undef SOURCE_MODULE
#undef MODULE_VERSION
#undef MODULE_DATE
#undef COPYRIGHT_HOLDER
#undef COPYRIGHT_DATE
#define ID_STRING_PREFIX "$Id: quickselect_loop_src.h ~|^` @(#)"
#define SOURCE_MODULE "quickselect_loop_src.h"
#define MODULE_VERSION "1.20"
#define MODULE_DATE "2018-04-18T04:09:58Z"
#define COPYRIGHT_HOLDER "Bruce Lilly"
#define COPYRIGHT_DATE "2017-2018"

/* Although the implementation is different, several concepts are adapted from:
   qsort -- qsort interface implemented by faster quicksort.
   J. L. Bentley and M. D. McIlroy, SPE 23 (1993) 1249-1265.
   Copyright 1993, John Wiley.
*/

/* local header files needed */
#include "quickselect_config.h" /* QUICKSELECT_INLINE */
#include "quickselect.h"        /* quickselect QSORT_FUNCTION_NAME */
#include "exchange.h"           /* EXCHANGE_SWAP protate */
#include "tables.h"             /* sampling_table_struct SAMPLING_TABLE_SIZE */
#if ! QUICKSELECT_BUILD_FOR_SPEED
#include "initialize_src.h"
#endif /* QUICKSELECT_BUILD_FOR_SPEED */

/* for assert.h */
#if ! ASSERT_CODE
# define NDEBUG 1
#endif

/* system header files */
#include <assert.h>             /* assert */
#include <errno.h>              /* errno E* (maybe errno_t [N1570 K3.2]) */
#include <limits.h>             /* *_MAX */
#include <stddef.h>             /* size_t NULL (maybe rsize_t) */
#if defined(__STDC__) && ( __STDC__ == 1) && defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
# include <stdint.h>            /* *int*_t (maybe RSIZE_MAX [N1570 K3.4]) */
# if __STDC_VERSION__ >= 201001L
    /* [N1570 6.10.8.1] (minimum value: y=0,mm=01) */
#  include <stdio.h>            /* (maybe errno_t rsize_t [N1570 K3.5]) */
#  include <stdlib.h>           /* (maybe errno_t rsize_t constraint_handler_t
                                   [N1570 K3.6]) */
# endif /* N1570 */
#endif /* C99 or later */

#if ASSERT_CODE + DEBUG_CODE
# include <stdio.h>
#endif

#if  __STDC_WANT_LIB_EXT1__
extern char quickselect_loop_src_file[];
extern char quickselect_loop_src_file_initialized;
#else
# if (ASSERT_CODE > 0) || ((DEBUG_CODE > 0) && defined(DEBUGGING))
/* not static; referenced by inline functions */
char quickselect_loop_src_file[PATH_MAX];
char quickselect_loop_src_file_initialized=0;
# define DEDICATED_SORT_SRC_FILE_HERE 1
# define INSERTION_SORT_SRC_FILE_HERE 1
# endif
#endif

/* dedicated_sort[_s] declaration */
#if ! defined(DEDICATED_SORT_DECLARED)
# if ! QUICKSELECT_BUILD_FOR_SPEED
QUICKSELECT_EXTERN
#else
static
# endif /* QUICKSELECT_BUILD_FOR_SPEED */
# include "dedicated_sort_decl.h"
;
# define DEDICATED_SORT_DECLARED 1
#endif /* DEDICATED_SORT_DECLARED */

#if ! QUICKSELECT_BUILD_FOR_SPEED
/* klimits declaration */
#include "klimits_decl.h"
;
/* partition declaration */
#include "partition_decl.h"
;
/* sample_index declaration */
#include "sample_index_decl.h"
;
/* sampling_table declaration */
#include "sampling_table_decl.h"
;
/* should_repivot declaration */
#include "should_repivot_decl.h"
;
#endif /* QUICKSELECT_BUILD_FOR_SPEED */

/* structures */
/* regions resulting from partitioning */
struct region_struct {
    size_t first;  /* base array */
    size_t beyond;
    size_t firstk; /* order statistics */
    size_t beyondk;
    unsigned char process; /* 0=false */
};

#include "dedicated_sort_src.h"

#include "pivot_src.h"

/* Special-case selection of minimum, maximum, or both. */
/* called from quickselect_loop */
/* Keeps track of (and relocates if necessary) elements comparing equal to the
   desired (minimum or maximum) element if ppeq,ppgt are not NULL.
*/
/* XXX might want this visible for test program, minmaxsort */
/* XXX or put code in a separate file, include here and there with macro
       to specify whether or not functions are static
*/
static QUICKSELECT_INLINE
void SELECT_MIN_FUNCTION_NAME(char *base,size_t first,size_t beyond,size_t size,
    COMPAR_DECL, void (*swapf)(char *, char *, size_t), size_t alignsize,
    size_t size_ratio, unsigned int options, char **ppeq, char **ppgt)
{
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
    if (DEBUGGING(SORT_SELECT_DEBUG)
    ||DEBUGGING(REPARTITION_DEBUG)
    ||DEBUGGING(REPIVOT_DEBUG)
    )
        (V) fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, ppeq=%p, "
            "ppgt=%p, optioons=0x%x */\n",__func__,quickselect_loop_src_file,__LINE__,
            (unsigned long)first,(unsigned long)beyond,(void *)ppeq,
            (void *)ppgt,options);
#endif
    if (beyond>first+1UL) {
        char *mn, *p, *q, *r;
        mn=p=base+first*size,q=p+size,r=base+beyond*size;
        /* both ppeq and ppgt are NULL, or both are non-NULL */
        A(((NULL==ppeq)&&(NULL==ppgt))||((NULL!=ppeq)&&(NULL!=ppgt)));
        if (NULL==ppeq) { /* non-partitioning */
            /* separate indirect/direct versions of loop to avoid repeated
               option testing in loop, cache dereferenced mn
            */
            if (0U!=(options&(QUICKSELECT_INDIRECT))) {
                char *x=*((char **)mn);
                for (; q<r; q+=size)
                    if (0<COMPAR(x,*((char **)q))) x=*((char **)(mn=q));
            } else
                for (; q<r; q+=size)
                    if (0<COMPAR(mn,q)) mn=q;
            if (mn!=p) {
#if QUICKSELECT_STABLE
                /* stability requires rotation rather than swaps */
                if (0U==((QUICKSELECT_STABLE)&options)) {
#endif /* QUICKSELECT_STABLE */
                    EXCHANGE_SWAP(swapf,p,mn,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
#if QUICKSELECT_STABLE
                } else {
                    /* |p     mn      | */
                    protate(p,mn,mn+size,size,swapf,alignsize,size_ratio);
                }
#endif /* QUICKSELECT_STABLE */
            }
        } else { /* partitioning for median-of-medians */
            /* sorting stability is not an issue if median-of-medians is used */
            /* separate indirect/direct versions of loop to avoid repeated
               option testing in loop, cache dereferenced mn
            */
            if (0U!=(options&(QUICKSELECT_INDIRECT))) {
                char *x=*((char **)mn);
                for (; q<r; q+=size) {
                    int c=COMPAR(x,*((char **)q));
                    if (0>c) continue;
                    if (0==c) {
                        mn+=size;
                        if (q==mn) continue;
                    } else /* 0<c */ mn=p;
                    A(mn!=q);
                    EXCHANGE_SWAP(swapf,mn,q,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                    x=*((char **)mn); /* new min */
                }
            } else {
                for (; q<r; q+=size) {
                    int c=COMPAR(mn,q);
                    if (0>c) continue;
                    if (0==c) {
                        mn+=size;
                        if (q==mn) continue;
                    } else /* 0<c */ mn=p; /* new min */
                    A(mn!=q);
                    EXCHANGE_SWAP(swapf,mn,q,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                }
            }
            if (NULL!=ppeq) *ppeq=p; /* leftmost min */
            if (NULL!=ppgt) *ppgt=mn+size; /* beyond rightmost min */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (DEBUGGING(SORT_SELECT_DEBUG)
            ||DEBUGGING(REPARTITION_DEBUG)
            ||DEBUGGING(REPIVOT_DEBUG)
            ) {
                (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, "
                    "ppeq=%p@%lu, ppgt=%p@%lu */\n",__func__,quickselect_loop_src_file,
                    __LINE__,(unsigned long)first,(unsigned long)beyond,
                    (void *)ppeq,(p-base)/size,(void *)ppgt,
                    (mn+size-base)/size);
                print_some_array(base,first,beyond-1UL,"/* "," */",options);
            }
#endif
        }
    } else { /* beyond==first+1UL; 1 element */
        if (NULL!=ppeq) *ppeq=base+first*size;
        if (NULL!=ppgt) *ppgt=base+beyond*size;
    }
}

/* XXX might want this visible for test program, minmaxsort */
static QUICKSELECT_INLINE
void SELECT_MAX_FUNCTION_NAME(char *base,size_t first,size_t beyond,size_t size,
    COMPAR_DECL, void (*swapf)(char *, char *, size_t), size_t alignsize,
    size_t size_ratio, unsigned int options, char **ppeq, char **ppgt)
{
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
    if (DEBUGGING(SORT_SELECT_DEBUG)
    ||DEBUGGING(REPARTITION_DEBUG)
    ||DEBUGGING(REPIVOT_DEBUG)
    )
        (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, ppeq=%p, "
            "ppgt=%p, options=0x%x */\n",__func__,quickselect_loop_src_file,__LINE__,
            (unsigned long)first,(unsigned long)beyond,(void *)ppeq,
            (void *)ppgt,options);
#endif
    if (beyond>first+1UL) {
        char *mx, *p, *r;
        p=base+first*size,mx=r=base+(beyond-1UL)*size;
        /* both ppeq and ppgt are NULL, or both are non-NULL */
        A(((NULL==ppeq)&&(NULL==ppgt))||((NULL!=ppeq)&&(NULL!=ppgt)));
        if ((NULL==ppeq)/*&&(NULL==ppgt)*/) { /* non-partitioning */
            /* separate indirect/direct versions of loop to avoid repeated
               option testing in loop, cache dereferenced mx
            */
            if (0U!=(options&(QUICKSELECT_INDIRECT))) {
                char *x=*((char **)mx);
                for (; p<r; p+=size)
                    if (0>COMPAR(x,*((char **)p))) x=*((char **)(mx=p));
            } else
                for (; p<r; p+=size)
                    if (0>COMPAR(mx,p)) mx=p;
            if (mx!=r) {
#if QUICKSELECT_STABLE
                /* stability requires rotation rather than swaps */
                if (0U==((QUICKSELECT_STABLE)&options)) {
#endif /* QUICKSELECT_STABLE */
                    EXCHANGE_SWAP(swapf,r,mx,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
#if QUICKSELECT_STABLE
                } else {
                    /* |      mx     r| */
                    protate(mx,mx+size,r+size,size,swapf,alignsize,size_ratio);
                }
#endif /* QUICKSELECT_STABLE */
            }
        } else { /* partitioning for median-of-medians */
            /* sorting stability is not an issue if median-of-medians is used */
            char *q;
            /* separate indirect/direct versions of loop to avoid repeated
               option testing in loop, cache dereferenced mx
            */
            if (0U!=(options&(QUICKSELECT_INDIRECT))) {
                char *x=*((char **)mx);
                for (q=r-size; q>=p; q-=size) {
                    int c=COMPAR(x,*((char **)q));
                    if (0<c) continue;
                    if (0==c) {
                        mx-=size;
                        if (q==mx) continue;
                    } else /* 0>c */ mx=r;
                    A(mx!=q);
                    EXCHANGE_SWAP(swapf,mx,q,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                    x=*((char **)mx); /* new max */
                }
            } else {
                for (q=r-size; q>=p; q-=size) {
                    int c=COMPAR(mx,q);
                    if (0<c) continue;
                    if (0==c) {
                        mx-=size;
                        if (q==mx) continue;
                    } else /* 0>c */ mx=r; /* new max */
                    A(mx!=q);
                    EXCHANGE_SWAP(swapf,mx,q,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                }
            }
            if (NULL!=ppeq) *ppeq=mx; /* leftmost max */
            if (NULL!=ppgt) *ppgt=r+size; /* beyond rightmost max */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (DEBUGGING(SORT_SELECT_DEBUG)
            ||DEBUGGING(REPARTITION_DEBUG)
            ||DEBUGGING(REPIVOT_DEBUG)
            ) {
                (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, "
                    "ppeq=%p@%lu, ppgt=%p@%lu */\n",__func__,quickselect_loop_src_file,
                    __LINE__,(unsigned long)first,(unsigned long)beyond,
                    (void *)ppeq,(mx-base)/size,(void *)ppgt,
                    (r+size-base)/size);
                print_some_array(base,first,beyond-1UL,"/* "," */",options);
            }
#endif
        }
    } else { /* beyond==first+1UL; 1 element */
        if (NULL!=ppeq) *ppeq=base+first*size;
        if (NULL!=ppgt) *ppgt=base+beyond*size;
    }
}

/* Recursive divide-and-conquer method to find both minimum and maximum.
   Split into two parts; (recursively) find minimum and maximum of each part.
   Overall minimum is the smaller of the two minima; overall maximum is the
   larger of the two maxima.
*/
/* XXX might want this visible for test program, minmaxsort */
static QUICKSELECT_INLINE
void FIND_MINMAX_FUNCTION_NAME(char *base, size_t first, size_t beyond,
    size_t size, COMPAR_DECL, unsigned int options, char **pmn, char **pmx)
{
    A(beyond>first);
    {
        size_t nmemb=beyond-first;
        if (1UL<nmemb) {
            char *mn, *mx;
            if (2UL<nmemb) {
                /* split; divide-and-conquer saves comparisons */
                size_t na=(nmemb>>1);
                char *mna, *mnb, *mxa, *mxb;
                /* find min and max of both parts */
                FIND_MINMAX_FUNCTION_NAME(base,first,first+na,size,COMPAR_ARGS,
                    options,&mna,&mxa);
                FIND_MINMAX_FUNCTION_NAME(base,first+na,beyond,size,COMPAR_ARGS,
                    options,&mnb,&mxb);
                /* overall min is smaller of *mna, *mnb; similarly for max */
                /* stability requires choosing mna if mna compares equal to mnb */
                if (0<OPT_COMPAR(mna,mnb,options)) mn=mnb; else mn=mna;
                /* stability requires choosing mxb if mxa compares equal to mxb */
                if (0<OPT_COMPAR(mxa,mxb,options)) mx=mxa; else mx=mxb;
            } else { /* nmemb==2UL */
                char *a, *z;
                /* first and last (i.e. second) elements */
                a=base+first*size,z=a+size;
                if (0<OPT_COMPAR(a,z,options)) mn=z,mx=a; else mn=a,mx=z; /* stable */
            }
            *pmn=mn, *pmx=mx;
        } else /* 1 element; min==max */
            *pmn=*pmx=base+first*size;
    }
}

/* Selection of both minimum and maximum using recursive find_minmax. */
/* XXX might want this visible for test program, minmaxsort */
static QUICKSELECT_INLINE
void SELECT_MINMAX_FUNCTION_NAME(char *base,size_t first,size_t beyond,size_t size,
    COMPAR_DECL, void (*swapf)(char *, char *, size_t), size_t alignsize,
    size_t size_ratio, unsigned int options)
{
    char *mn, *mx, *a, *z;
    A(beyond>first);
    /* first and last elements */
    a=base+first*size,z=base+(beyond-1UL)*size;
    FIND_MINMAX_FUNCTION_NAME(base,first,beyond,size,COMPAR_ARGS,options,&mn,&mx);
    /* put min and max in place with at most 2 swaps */
    /* stability requires rotation rather than swaps */
    /* +----------------------------------+ */
    /* |                                  | */
    /* +----------------------------------+ */
    /* +a         x               n      z+ */
    /* nothing to do if mx and mn are in place, i.e. mn==a and mx==z */
    if ((mn!=a)||(mx!=z)) {
        /* special case: mx==a and mn==z */
        if ((mx==a)&&(mn==z)) {
            EXCHANGE_SWAP(swapf,a,z,size,alignsize,size_ratio,
                SWAP_COUNT_STATEMENT);
        } else { /* rotations required to preserve stability */
#if QUICKSELECT_STABLE
            if (0U!=((QUICKSELECT_STABLE)&options)) {
                if (a!=mn) {
                    protate(a,mn,mn+size,size,swapf,alignsize,size_ratio);
                    if (mx<mn) mx+=size; /* mx was moved by rotation */
                }
                if (z!=mx)
                    protate(mx,mx+size,z+size,size,swapf,alignsize,size_ratio);
            } else {
#endif /* QUICKSELECT_STABLE */
                if (a!=mn) {
                    EXCHANGE_SWAP(swapf,a,mn,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                }
                if (z!=mx) { /* beware case where a was mx before above swap! */
                    EXCHANGE_SWAP(swapf,z,a==mx?mn:mx,size,alignsize,size_ratio,
                        SWAP_COUNT_STATEMENT);
                }
#if QUICKSELECT_STABLE
            }
#endif /* QUICKSELECT_STABLE */
        }
    }
}

/* function to consolidate logic and calls to special-case selection functions */
/* also sets sampling table, determines whether to sort */
static QUICKSELECT_INLINE
int special_cases(char *base, size_t first, size_t beyond, size_t size,
    COMPAR_DECL, void (*swapf)(char *, char *, size_t), size_t alignsize,
    size_t size_ratio, size_t nmemb, const size_t *pk, size_t firstk,
    size_t beyondk, size_t cachesz, size_t pbeyond, unsigned int options,
    char **ppeq, char **ppgt, struct sampling_table_struct **ppst,
    const size_t **ppk, unsigned int *pindex)
{
    int ret=1; /* caller continues */
    size_t nk=beyondk-firstk;
    /* Check for special-case selection: 1-2 order statistic ranks */
    if ((3UL>nk)&&((2UL>nk)||(NULL==ppeq))) {
        size_t fk=pk[firstk],  /* first (smallest) rank requested */
            ek=pk[beyondk-1UL],/* end rank requested */
            sp=first+1UL,      /* second element rank */
            lp=beyond-1UL,     /* last element rank */
            pp=beyond-2UL;     /* penultimate element rank */
#if (DEBUG_CODE > 0)
        if ((0UL==nk)||(ek<first)||(fk>=beyond)||(ek<fk)) {
            (V)fprintf(stderr,
                "/* %s: %s line %d: (0==nk)||(ek<first)||(fk>=beyond)||(ek<fk):"
                " first=%lu, beyond=%lu, pk=%p, firstk=%lu, beyondk=%lu, nk=%lu"
                ", fk=%lu, ek=%lu */\n",__func__,quickselect_loop_src_file,__LINE__,first,
                beyond,(const void *)pk,firstk,beyondk,nk,fk,ek);
        }
#endif
        A(fk>=first);A(ek<beyond); /* arg sanity */
        A((beyondk==firstk+1UL)||(fk!=ek)); /* no duplicate rank requests */
        switch (nk) {
            case 1UL : /* any of smallest 2 or largest 2 */
                if ((fk==first)||(fk==sp)) {
                    SELECT_MIN_FUNCTION_NAME(base,first,beyond,size,
                        COMPAR_ARGS,swapf,alignsize,size_ratio,options,ppeq,ppgt);
                    if (fk==sp) {
                        SELECT_MIN_FUNCTION_NAME(base,sp,beyond,size,
                            COMPAR_ARGS,swapf,alignsize,size_ratio,options,ppeq,
                            ppgt);
                        if ((NULL!=ppeq/*)&&(NULL!=ppgt)*/)
                        &&(0==OPT_COMPAR(*ppeq-size,*ppeq,options)))
                            (*ppeq)-=size;
                    }
                    return 0 ;
                } else if ((ek==lp)||(ek==pp)) {
                    SELECT_MAX_FUNCTION_NAME(base,first,beyond,size,COMPAR_ARGS,
                        swapf,alignsize,size_ratio,options,ppeq,ppgt);
                    if (ek==pp) {
                        SELECT_MAX_FUNCTION_NAME(base,first,lp,size,COMPAR_ARGS,
                            swapf,alignsize,size_ratio,options,ppeq,ppgt);
                        if ((NULL!=ppeq/*)&&(NULL!=ppgt)*/)
                        &&(0==OPT_COMPAR(*ppeq,*ppgt,options)))
                            (*ppgt)+=size;
                    }
                    return 0 ;
                }
            break;
            case 2UL : /* 2 smallest, 2 largest, or smallest & largest */
                A(NULL==ppeq);
                if (fk==first) {
                    if (ek==lp) { /* smallest & largest */
                        SELECT_MINMAX_FUNCTION_NAME(base,first,beyond,size,
                            COMPAR_ARGS,swapf,alignsize,size_ratio,options);
                        return 0 ;
                    } else if (ek==sp) { /* 2 smallest */
                        SELECT_MIN_FUNCTION_NAME(base,first,beyond,size,
                            COMPAR_ARGS,swapf,alignsize,size_ratio,options,NULL,
                            NULL);
                        SELECT_MIN_FUNCTION_NAME(base,sp,beyond,size,
                            COMPAR_ARGS,swapf,alignsize,size_ratio,options,NULL,
                            NULL);
                        return 0 ;
                    }
                } else if ((fk==pp)&&(ek==lp)) { /* 2 largest */
                    SELECT_MAX_FUNCTION_NAME(base,first,beyond,size,COMPAR_ARGS,
                        swapf,alignsize,size_ratio,options,NULL,NULL);
                    SELECT_MAX_FUNCTION_NAME(base,first,lp,size,COMPAR_ARGS,
                        swapf,alignsize,size_ratio,options,NULL,NULL);
                    return 0 ;
                }
            break;
        }
    }
    A(*pindex < (SAMPLING_TABLE_SIZE));
    *ppst=SAMPLING_TABLE_FUNCTION_NAME(first,beyond,pk,firstk,beyondk,ppeq,ppk,
        nmemb,options);
    return ret;
}

/* Update order statistic ranks array limits. */
static QUICKSELECT_INLINE
void rank_tests(char *base, size_t first, size_t p, size_t q,
    size_t beyond, size_t size, const size_t *pk, size_t firstk,
    size_t beyondk, size_t *plk, size_t *prk, char **ppeq, char **ppgt)
{
    /* revised range of order statistic ranks (always) */
    /* < region indices [first,p), order statistics [firstk,lk) */
    /* > region indices [q,beyond), order statistics [rk,beyondk) */
    KLIMITS_FUNCTION_NAME(p,q,pk,firstk,beyondk,plk,prk);
    /* Special-case below only for median-of-medians w/ region extents for
       avoidance of recomparisons after median selection.
    */
    if ((0UL==firstk)&&(1UL==beyondk)&&(NULL!=ppeq)) {
        /* Only applicable for median-of-medians (one order statistic (the
           median) with non-NULL ppeq and ppgt pointers); extents of region
           containing the median.
        */
        size_t r=pk[0]; /* desired rank */
        A(p<q);A(first<=p);A(q<=beyond);
        /*Update range pointers if median (of medians) is [in] one of 3 regions.
          This is the only place where the extents (ppeq and ppgt) are updated;
          when the desired (median of medians) rank is in the = region or is the
          only element in the < or > region.
        */
        if ((p<=r)&&(r<q)) /* in = region */
            *ppeq=base+p*size, *ppgt=base+q*size;
        else if ((first+1UL==p)&&(first<=r)&&(r<p)) /* < region only element */
            *ppeq=base+first*size, *ppgt=base+p*size;
        else if ((q+1UL==beyond)&&(q<=r)&&(r<beyond)) /* > region only element */
            *ppeq=base+q*size, *ppgt=base+beyond*size;
        /* If the extents are set, none of the regions from this partition need
           be (and will not be) further partitioned.  Otherwise, only the region
           containing the median's (of medians) rank will be processed.
        */
    }
    A(*plk>=firstk);A(*prk<=beyondk);A(*plk<=*prk);
}

/* quickselect_loop definition (internal interface) */
/* Never called for nmemb<2UL. */

#if  __STDC_WANT_LIB_EXT1__
/* Preliminary support for 9899:201x draft N1570 qsort_s w/ "context".
   "context" is similar to glibc qsort_r; N1570 also has provision for
   runtime-constraint violation detection and handling. "Preliminary"
   because of the apparent lack of a convincing use-case for "context" and
   due to the poorly defined semantics and interface for constraint
   violation handling.

   Consequences of "context" are wide-ranging: any operation that requires
   comparisons (pivot selection, partitioning, dedicated sorting and/or
   selection, and support functions for any of those) has to be rewritten.
   The only operations unaffected are sampling, basic swaps, blockmoves using
   swaps, rank comparisons, and partition size evaluation; sampling and
   repivoting tables may also be reused without change.
   Executable code size is roughly doubled, not including external
   constraint-handler function code.
   Use case of "context" is questionable; one could simply use an appropriate
   comparison function.  Published supposed examples (e.g.
   https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort-s
   tend to be rather silly (in the specific example above:
      1. functions are defined for specific locales, but not specifically
         implementing locale-specific collation -- one could at least as easily
         define locale-specific string comparison functions using the standard
         strcoll [+] function and use these with qsort to perform the
         locale-specific sorts with no need for "context", and avoiding the
         other implementation issues detailed below.
      2. Aside from inconsistent "context" argument order...
      3. ... the implementation comparison function copies (!) (leading portions
         of) supplied strings to fixed size (!!)[*] local buffers, then makes a
         second set of passes (!!!) over the copies to perform a conversion
         (which is discarded (!!!!) when the comparison function returns), which
         is then subjected to a third (!!!!!) pass to perform the comparison.
         Note that qsort implementations typically call the comparison function
         N log N times for an array of N elements; the above implementation
         makes 2 N log N copies and 6 N log N passes over data representing
         the strings to be sorted.  In particular, at each stage of partitioning
         qsort implementations compare a pivot element to many other elements;
         in the above implementation the string corresponding to that pivot
         element is copied, the copy modified and examined, only to be discarded
         before repeating those steps anew with the same pivot element's string
         for the next comparison (N-1 times for each partition of N elements).
      4. Although the copies (see #3 above) ignore the actual length of the
         original strings, strlen is subsequently called for each string (copy),
         resulting in a fourth (!!!!!!) pass over the data. Had strlen been
         called for the initial strings, the copies could have been made
         appropriate sizes (assuming that one still naively wished to make, then
         discard such copies).
      5. "context" is declared as void *, not const void *, which implies that
         either the qsort_s implementation or the called comparison function
         may modify the object pointed to by "context", which invites
         non-deterministic, non-repeatable, (i.e. unspecified and undefined)
         behavior.
      * a possibly-valid use of "context" *might* be to provide the maximum
        string length, avoiding magic numbers and failure to fully compare
        strings which have long identical leading substrings... *if* one
        insisted on the naive implementation involving copies (which are
        subsequently discarded) and multiple passes over the data.  It would
        be much more efficient to make one-time initial transformations (e.g.
        w/ strxfrm [+]) of the original string data supplemented by an index
        indicating the original order (or a pointer to the original string
        data), sorting the transformed and supplemented data using standard
        strcmp on the transformed strings.  That would involve N combined
        transformations and copies (instead of N log N copies and N log N
        transformations) plus N log N standard strcmp string comparisons (rather
        than 6 N log N passes over data), followed by access of the orginal
        string data via the indices or pointers for output, or rearrangement
        of the original string data based on the indices associated with the
        sorted transformed strings.
      + Note that strcoll and strxfrm have been standardized since C89 (a.k.a.
        C90).
   ). In summary, there is no convincing use-case for "context" to justify
   doubling the size of library code.

   Runtime-constraint violation detection is OK, but error handling is poorly
   defined.  It is unclear whether the handler is supposed to be global, or
   per-process, or per-thread.  The only interface is set_constraint_handler_s,
   which changes the handler; there is no way to determine what the handler is
   (e.g. in order to actually call it) without (at least potentially) changing
   it.  It may be possible to reset it (provided no other process or thread made
   an intervening change), but there is an inherent window of vulnerability.
   No provision is made for mutexes or other synchronization mechanisms to avoid
   the vulnerability.
*/
#endif /* __STDC_WANT_LIB_EXT1__ */

/* definition */
# include "quickselect_loop_decl.h"
{
    QUICKSELECT_RETURN_TYPE ret=0;
    auto int c=0; /* repivot factor2 count for iterative operation */
    size_t nmemb;
    struct sampling_table_struct *pst=sorting_sampling_table;

#if ! QUICKSELECT_BUILD_FOR_SPEED
    if ((char)0==file_initialized) initialize_file(__FILE__);
#endif /* QUICKSELECT_BUILD_FOR_SPEED */
#if (ASSERT_CODE > 0) || ((DEBUG_CODE > 0) && defined(DEBUGGING))
    if ((char)0==quickselect_loop_src_file_initialized) {
        (V)path_basename(__FILE__,quickselect_loop_src_file,PATH_MAX);
        quickselect_loop_src_file_initialized++;
    }
#endif
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
    if (DEBUGGING(SORT_SELECT_DEBUG)||DEBUGGING(REPIVOT_DEBUG)) {
        if (NULL!=pk)
            (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, pk=%p,"
                " firstk=%lu, beyondk=%lu, pk[%lu]=%lu, pk[%lu]=%lu, ppeq=%p, "
                "ppgt=%p */\n",__func__,quickselect_loop_src_file,__LINE__,first,beyond,
                (const void *)pk,firstk,beyondk,firstk,pk[firstk],beyondk-1UL,
                pk[beyondk-1UL],(void *)ppeq,(void *)ppgt);
        else
            (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, "
                "pk=NULL */\n",__func__,quickselect_loop_src_file,__LINE__,first,beyond);
    }
#endif
    A(first<beyond);
    nmemb=beyond-first;
    A(2UL<=nmemb);
    /* ppeq,ppgt consistency: both or neither NULL */
    A(((NULL==ppeq)&&(NULL==ppgt))||((NULL!=ppeq)&&(NULL!=ppgt)));
    for (; 2UL<=nmemb;) { /* loop until done */
        char *pc, *pd, *pe, *pf, *pivot;
        struct region_struct lt_region, gt_region, *ps_region, *pl_region;

#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(SORT_SELECT_DEBUG)) (V) fprintf(stderr,
            "/* %s: %s line %d: first=%lu, beyond=%lu, nmemb=%lu, "
            "table_index=%u */\n",
            __func__,quickselect_loop_src_file,__LINE__,first,beyond,nmemb,table_index);
#endif
        A(table_index < (SAMPLING_TABLE_SIZE));
        if (NULL!=pk) { /* selection only */
            /* Check for special-case selection: 1-2 order statistic ranks */
            if (0==special_cases(base,first,beyond,size,COMPAR_ARGS,swapf,
                alignsize,size_ratio,nmemb,pk,firstk,beyondk,cachesz,pbeyond,
                options,ppeq,ppgt,&pst,&pk,&table_index))
                return ret ;
            A((SAMPLING_TABLE_SIZE)>table_index);
            A((0U==table_index)||(nmemb>pst[table_index-1U].max_nmemb));
        }

        /* Separate test, not else clause; special_cases may change pk. */
        if (NULL==pk) { /* sorting only */
            A(pst==sorting_sampling_table); A(NULL==ppeq);
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (nmemb<=quickselect_small_array_cutoff) {
#endif
                ret= DEDICATED_SORT(base,first,beyond,size,COMPAR_ARGS,
                    swapf,alignsize,size_ratio,table_index,cachesz,pbeyond,
                    options);
                switch (ret) {
                    case 0 : /* sorting is complete */
                    return ret ;
                    case EINVAL : /* error */
#if ASSERT_CODE + DEBUG_CODE
                        fflush(stderr); fflush(stdout);
                        (V)fprintf(stderr,
                            "/* %s: line %d: EINVAL return %d from "
                            "dedicated_sort */\n",
                            __func__,__LINE__,ret);
                        A(ret!=EINVAL);
#endif
                    return ret ;
                    case EAGAIN : /* continue with divide-and-conquer */
                        ret = 0; /* for quickselect_loop return */
                    break;
                    default : /* ? */
#if ASSERT_CODE + DEBUG_CODE
                        fflush(stderr); fflush(stdout);
                        (V)fprintf(stderr,
                            "/* %s: line %d: unexpected return %d from "
                            "dedicated_sort */\n",
                            __func__,__LINE__,ret);
                        A(ret==0);
#endif
                    return ret ;
                }
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            }
#endif
        }

        /* Divide-and-conquer; set sampling table index. */
        table_index=SAMPLE_INDEX_FUNCTION_NAME(pst, table_index, nmemb);

#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(SORT_SELECT_DEBUG)) (V) fprintf(stderr,
            "/* %s: %s line %d: first=%lu, beyond=%lu, nmemb=%lu, "
            "table_index=%u */\n",
            __func__,quickselect_loop_src_file,__LINE__,first,beyond,nmemb,table_index);
#endif
#if ASSERT_CODE
        if (nmemb>pst[table_index].max_nmemb)
            (V)fprintf(stderr,"%s: %s line %d: nmemb=%lu, table_index=%u, "
                "pst[%u].max_nmemb=%lu */\n",__func__,quickselect_loop_src_file,__LINE__,
                nmemb,table_index,table_index,pst[table_index].max_nmemb);
        A(pst[table_index].max_nmemb>=nmemb);
        if ((0U<table_index)&&(nmemb<=pst[table_index-1U].max_nmemb))
            (V)fprintf(stderr,"%s: %s line %d: nmemb=%lu, table_index=%u, "
                "pst[%u].max_nmemb=%lu */\n",__func__,quickselect_loop_src_file,__LINE__,
                nmemb,table_index,table_index-1U,pst[table_index-1U].max_nmemb);
        A((0U==table_index)||(pst[table_index-1U].max_nmemb<nmemb));
#endif /* ASSERT_CODE */

#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        /* antiqsort handshake */
        /* freeze low-address samples which will be used for pivot selection */
        if (aqcmp==compar)
            (V)freeze_some_samples(base,first,beyond,size,compar,swapf,
                alignsize,size_ratio,table_index,options);
#endif

#if defined(DEBUGGING)
        /* count repivots */
        if (0U!=((QUICKSELECT_RESTRICT_RANK)&options)) {
            nrepivot++;
# if (DEBUG_CODE > 0)
            if (DEBUGGING(SORT_SELECT_DEBUG)||DEBUGGING(SHOULD_REPIVOT_DEBUG))
                (V)fprintf(stderr,"/* %s: %s line %d: repivoting region "
                    "first=%lu, beyond=%lu, firstk=%lu, beyondk=%lu, "
                    "options=0x%x */\n",__func__,quickselect_loop_src_file,__LINE__,first,
                    beyond,firstk,beyondk,options);
# endif
        }
#endif

        /* select a pivot element */
        pivot=SELECT_PIVOT_FUNCTION_NAME(base,first,beyond,size,COMPAR_ARGS,
            swapf,alignsize,size_ratio,table_index,pk,cachesz,pbeyond,options,
            &pc,&pd,&pe,&pf);
        A(NULL!=pivot);
        if (NULL==pivot) {
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            fprintf(stderr,"/* %s: line %d: NULL pivot */\n",__func__,__LINE__);
            abort();
#endif
            return ret=errno;
        }
#if ASSERT_CODE
        if ((pivot<base+first*size)||(pivot>=base+beyond*size)) {
            (V)fprintf(stderr, "/* %s: %s line %d: pivot=%p(%d), pl=%p, pu=%p */\n",
                __func__,quickselect_loop_src_file,__LINE__,(void *)pivot,*((int *)pivot),
                base+first*size,base+beyond*size);
            print_some_array(base,first,beyond-1UL, "/* "," */",options);
        }
#endif /* ASSERT_CODE */
        A(NULL!=pivot);A(base+first*size<=pivot);A(pivot<base+beyond*size);
        A(pc<=pd);A(pd<pe);A(pe<=pf);A(pd<=pivot);A(pivot<pe);
#if ((DEBUG_CODE)>0) && defined(DEBUGGING)
        if (DEBUGGING(REPIVOT_DEBUG)||DEBUGGING(PIVOT_SELECTION_DEBUG)) {
            size_t x=(pivot-base)/size;
            (V)fprintf(stderr, "/* %s: pivot=%p[%lu] */\n",
                __func__,(void *)pivot,x);
            if (pivot!=base+size*x)
                (V)fprintf(stderr, "/* %s: pivot %p is misaligned: %p */\n",
                    __func__,pivot,base+size*x);
            if (nmemb<=MAX_ARRAY_PRINT)
                print_some_array(base,first,beyond-1UL, "/* "," */",options);
        }
#endif

        /* Partition the array around the pivot element into less-than,
           equal-to, and greater-than (w.r.t. the pivot) regions.  The
           equal-to region requires no further processing.
        */
        lt_region.first=first, gt_region.beyond=beyond;
        PARTITION_FUNCTION_NAME(base,first,beyond,pc,pd,pivot,pe,pf,size,
            COMPAR_ARGS,swapf,alignsize,size_ratio,cachesz,options,
            &(lt_region.beyond),&(gt_region.first));
        /* regions: < [first,lt_region.beyond)
                    > [gt_region.first,beyond)
        */
        A(lt_region.beyond<gt_region.first);A(lt_region.beyond<=beyond);
        A(lt_region.first<=lt_region.beyond);
        A(gt_region.first<=gt_region.beyond);A(first<=gt_region.first);
#if ((DEBUG_CODE)>0) && defined(DEBUGGING)
        if (DEBUGGING(CORRECTNESS_DEBUG)) {
            size_t x;
            x=test_array_partition(base,first,lt_region.beyond,
                gt_region.first-1UL,beyond,size,compar,options,NULL,NULL);
            if (x!=lt_region.beyond) {
                (void)fprintf(stderr,"/* %s: line %d: bad partition at %lu, "
                    "pivot at %lu */\n",__func__,__LINE__,
                    x,lt_region.beyond);
                print_some_array(base,first,beyond-1UL,"/* ",
                    " */",options);
                abort();
            }
        }
#endif

        if (NULL!=pk) { /* selection only */
            rank_tests(base,first,lt_region.beyond,gt_region.first,beyond,size,
                pk,firstk,beyondk,&(lt_region.beyondk),&(gt_region.firstk),ppeq,
                ppgt);
            lt_region.firstk=firstk, gt_region.beyondk=beyondk;
        }
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        else /* sorting */
            /* for graphing ratios during sorting */
            lt_region.firstk=lt_region.beyondk=gt_region.firstk=gt_region.beyondk=0UL;
#endif

        /* Which region(s) should be processed? */
        lt_region.process=(((lt_region.first+1UL<lt_region.beyond)
            &&((NULL==pk)||(lt_region.firstk<lt_region.beyondk)))?1U:0U);
        gt_region.process=(((gt_region.first+1UL<gt_region.beyond)
            &&((NULL==pk)||(gt_region.firstk<gt_region.beyondk)))?1U:0U);

        /* Categorize less-than and greater-than regions as small and large. */
        if (lt_region.beyond-lt_region.first<gt_region.beyond-gt_region.first) {
            ps_region=&lt_region, pl_region=&gt_region;
        } else {
            ps_region=&gt_region, pl_region=&lt_region;
        }

        if (0U!=((QUICKSELECT_RESTRICT_RANK)&options))
            c=0; /* reset factor2 count if pivot was median-of-medians */
        /* default pivot selection uses array SAMPLES */
        options &= ~(QUICKSELECT_RESTRICT_RANK);

        /* Process less-than and/or greater-than regions by relative size. */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(PARTITION_DEBUG)) {
            (V)fprintf(stderr,"/* %s: %s line %d: small region from partition "
                "of nmemb=%lu, s=%lu, e=%lu, t=%lu, pk=%p, firstk=%lu, beyondk="
                "%lu, ppeq=%p%s */\n",__func__,quickselect_loop_src_file,__LINE__,nmemb,
                ps_region->beyond-ps_region->first,
                gt_region.first-lt_region.beyond,
                pl_region->beyond-pl_region->first,
                (const void *)pk, ps_region->firstk, ps_region->beyondk,
                (void *)ppeq, (0U==ps_region->process)?" (ignored)":"");
        }
        if (((NULL==ppeq)||(DEBUGGING(PARTITION_DEBUG)))
           &&(DEBUGGING(PARTITION_ANALYSIS_DEBUG))
        ) { /* for graphing ratios during sorting */
            size_t r=pl_region->beyond-pl_region->first;
            (V)fprintf(stderr,"/* %s: %s line %d: regions from partition of nme"
                "mb=%lu, s=%lu, e=%lu, t=%lu, table_index=%u, samples=%lu, "
                "pk=%p, ppeq=%p, firstk=%lu, beyondk=%lu, count=%d, ratio=%lu%s"
                " */\n",__func__,quickselect_loop_src_file,__LINE__,nmemb,
                ps_region->beyond-ps_region->first,
                gt_region.first-lt_region.beyond, r,
                table_index, pst[table_index].samples,
                (const void *)pk, (void *)ppeq,
                pl_region->firstk, pl_region->beyondk,
                c, r/(nmemb-r),(0U==pl_region->process)?" (ignored)":"");
        }
#endif
        if (0U!=pl_region->process) { /* Process large region. */
            if (0U!=ps_region->process) { /* Recurse on small region. */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
                if (DEBUGGING(SORT_SELECT_DEBUG))
                    (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu"
                        ", nmemb=%lu, table_index=%u, both regions (%lu) */\n",
                        __func__,quickselect_loop_src_file,__LINE__,first,
                        beyond,nmemb,table_index,ps_region->first);
#endif
#if defined(DEBUGGING)
                nrecursions++;
#endif
#if (DEBUG_CODE > 0)
                if (NULL!=pk) {
                    if ((pk[ps_region->beyondk-1UL]<ps_region->first)
                       ||(pk[ps_region->firstk]>=ps_region->beyond)
                    ) {
                        (V)fprintf(stderr,"/* %s: %s line %d: (0==nk)||"
                            "(ek<first)||(fk>=beyond)||(ek<fk): first=%lu, "
                            "beyond=%lu, pk=%p, firstk=%lu(%lu), beyondk=%lu"
                            "(-1:%lu) */\n",__func__,quickselect_loop_src_file,__LINE__,
                            ps_region->first,ps_region->beyond,(const void *)pk,
                            ps_region->firstk,pk[ps_region->firstk],
                            ps_region->beyondk,pk[ps_region->beyondk-1UL]);
                     }
                 }
#endif
                /* The small region will use a table index no larger than was
                   used for the current sub-array; the current table_index is a
                   reasonable starting point to find the index for the small
                   region (and for the large region).
                */
                ret= QUICKSELECT_LOOP(base,ps_region->first,ps_region->beyond,size,
                    COMPAR_ARGS,pk,ps_region->firstk,ps_region->beyondk,swapf,
                    alignsize,size_ratio,table_index,cachesz,pbeyond,options,
                    ppeq,ppgt);
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
                if (DEBUGGING(SORT_SELECT_DEBUG))
                    (V)fprintf(stderr,"/* %s: %s line %d: ps_region->first=%lu,"
                        " ps_region->beyond=%lu: quickselect_loop returned %d "
                        "*/\n",__func__,quickselect_loop_src_file,__LINE__,
                        ps_region->first,ps_region->beyond,ret);
#endif
                A(0==ret);
                if(0!=ret) return ret;
            }
            /* Iterate on large region. */
            first=pl_region->first, beyond=pl_region->beyond,
                firstk=pl_region->firstk, beyondk=pl_region->beyondk;
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (DEBUGGING(SORT_SELECT_DEBUG))
                (V)fprintf(stderr,"/* %s: %s line %d: large region [%lu,%lu) "
                    "*/\n",__func__,quickselect_loop_src_file,__LINE__,first,
                    beyond);
            if (0U!=((QUICKSELECT_RESTRICT_RANK)&options)) {
                if (DEBUGGING(SORT_SELECT_DEBUG)||DEBUGGING(SHOULD_REPIVOT_DEBUG))
                    (V)fprintf(stderr,"/* %s: %s line %d: restricted rank flag "
                        "not reset: first=%lu, beyond=%lu, firstk=%lu, beyondk="
                        "%lu, options=0x%x */\n",__func__,quickselect_loop_src_file,__LINE__,
                        first,beyond,firstk,beyondk,options);
            }
#endif
        } else /* large region to be ignored; maybe iterate small region */
            /* Don't be distracted by comments; pay attention to the braces! */
        if (0U!=ps_region->process) { /* Iterate on small region. */
            first=ps_region->first, beyond=ps_region->beyond,
                firstk=ps_region->firstk, beyondk=ps_region->beyondk;
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (DEBUGGING(REPARTITION_DEBUG))
                (V)fprintf(stderr,"/* %s: %s line %d: small region: first=%lu, "
                    "beyond=%lu, firstk=%lu, beyondk=%lu: %s */\n",__func__,
                    quickselect_loop_src_file,__LINE__,first,beyond,firstk,beyondk,
                    "continuing");
#endif
        } else {
            /* not processing small region (nor large region) */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
            if (DEBUGGING(REPARTITION_DEBUG))
                (V)fprintf(stderr,"/* %s: %s line %d: %s */\n",__func__,
                    quickselect_loop_src_file,__LINE__,"done");
#endif
            if (NULL!=ppeq) { A(NULL!=*ppeq); A(NULL!=*ppgt); }
            return ret ; /* Process neither; nothing left to do. */
        }
        /* remaining region processing */
        A(first<beyond);
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(SORT_SELECT_DEBUG)) (V) fprintf(stderr,
            "/* %s: %s line %d: first=%lu, beyond=%lu, nmemb=%lu, "
            "table_index=%u */\n",
            __func__,quickselect_loop_src_file,__LINE__,first,beyond,nmemb,table_index);
#endif
        /* Only if iterating on the large region, determine whether or not a
           robust pivot selection method should be used.
        */
        if (first==pl_region->first) {
            /* Should large region be repivoted? */
            /* Determine whether or not to repivot/repartition region of size r
               elements (large region) resulting from a partition of nmemb
               elements.  Assumed that continued processing of the region w/o
               repivoting will yield a similarly poor split.  Repivot if the
               cost of repivoting plus processing the resulting regions is
               expected to be less than the cost of processing the region w/o
               repivoting.
            */
            if (0U==(options&(QUICKSELECT_NO_REPIVOT)))
                options|=SHOULD_REPIVOT_FUNCTION_NAME(nmemb,beyond-first,pst,
                    table_index,pk,&c,ppeq);
        }
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(REPARTITION_DEBUG))
            (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, firstk"
                "=%lu, beyondk=%lu: %s */\n",__func__,quickselect_loop_src_file,__LINE__,
                first,beyond,firstk,beyondk,"continuing");
#endif
        nmemb=beyond-first; /* update nmemb after should_repivot call */
#if (DEBUG_CODE > 0) && defined(DEBUGGING)
        if (DEBUGGING(SORT_SELECT_DEBUG))
            (V)fprintf(stderr,"/* %s: %s line %d: first=%lu, beyond=%lu, nmemb="
                "%lu, table_index=%u */\n",__func__,quickselect_loop_src_file,__LINE__,first,
                beyond,nmemb,table_index);
#endif
        A(nmemb==beyond-first);
    }
    return ret;
}
#endif /* QUICKSELECT_LOOP_SRC_H_INCLUDED */
